### ISSUE TITLE
Could not initialize class SharedDriver

### ISSUE THREAD

**Issue by jkleiser** [cucumber/cucumber-jvm#1033]
I'm trying to run the github.com/cucumber/cucumber-jvm/tree/master/examples/java-webbit-websockets-selenium on my Mac (10.11.6) doing `mvn install`, but I get the error `Could not initialize class cucumber.examples.java.websockets.SharedDriver`. A Firefox window comes up, but closes after some time (55.393 s). The last thing I tried was installing the new geckodriver v0.9.0 from github.com/mozilla/geckodriver/releases, but I get the same error. (I'm not sure where to put the DesiredCapabilities for this geckodriver.) My Java version is 1.8.0_66.
If there is no easy fix for this example, then I would be glad to be directed to some other simple Cucumber-JVM-web example (Scala-Play-sbt if possible).

Here the final part from the console:

```
Scenario: 100 Fahrenheit to Celcius  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class cucumber.examples.java.websockets.SharedDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
    at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
    at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
    at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
    at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
    at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
    at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
    at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
    at cucumber.runtime.java.picocontainer.PicoFactory.getInstance(PicoFactory.java:37)
    at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
    at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
    at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
    at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
    at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
    at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)


Results :

Tests in error: 
  null
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver
  Could not initialize class cucumber.examples.java.websockets.SharedDriver

Tests run: 15, Failures: 0, Errors: 6, Skipped: 9

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.156 s
[INFO] Finished at: 2016-08-01T09:38:33+02:00
[INFO] Final Memory: 13M/143M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project java-webbit-websockets-selenium: There are test failures.
[ERROR] 
[ERROR] Please refer to /Volumes/P3/Cucumber/cucumber-jvm/examples/java-webbit-websockets-selenium/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by jkleiser** [comment]
I just ran `mvn test` at the top level `cucumber-jvm`, and here all tests seemed to pass except the final re. Java8. Here's some lines from the console:
```
Tests in error: 
  Failed to instantiate class cucumber.runtime.java8.test.LambdaStepdefs

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Cucumber-JVM ....................................... SUCCESS [  0.171 s]
[INFO] Cucumber-JVM: Core ................................. SUCCESS [  8.395 s]
[INFO] Cucumber-JVM: JUnit ................................ SUCCESS [  1.075 s]
[INFO] Cucumber-JVM: Java ................................. SUCCESS [ 10.769 s]
[INFO] Cucumber-JVM: TestNG ............................... SUCCESS [  4.418 s]
[INFO] Cucumber-JVM: PicoContainer ........................ SUCCESS [  0.987 s]
[INFO] Cucumber-JVM: Clojure .............................. SUCCESS [ 52.999 s]
[INFO] Cucumber-JVM: JRuby ................................ SUCCESS [  8.940 s]
[INFO] Cucumber-JVM: Jython ............................... SUCCESS [  7.990 s]
[INFO] Cucumber-JVM: Spring ............................... SUCCESS [  4.714 s]
[INFO] Cucumber-JVM: OSGi ................................. SUCCESS [  1.604 s]
[INFO] Cucumber-JVM: Guice ................................ SUCCESS [  2.303 s]
[INFO] Cucumber-JVM: Weld ................................. SUCCESS [  4.059 s]
[INFO] Cucumber-JVM: Groovy ............................... SUCCESS [ 24.563 s]
[INFO] Cucumber-JVM: Rhino ................................ SUCCESS [  1.141 s]
[INFO] Cucumber-JVM: OpenEJB .............................. SUCCESS [ 14.043 s]
[INFO] Cucumber-JVM: Scala Aggregator ..................... SUCCESS [  0.005 s]
[INFO] Cucumber-JVM: Scala (2.11) ......................... SUCCESS [ 37.714 s]
[INFO] Cucumber-JVM: Scala (2.10) ......................... SUCCESS [ 17.567 s]
[INFO] Cucumber-JVM: Scala (2.12) ......................... SUCCESS [ 18.505 s]
[INFO] Cucumber-JVM: Needle ............................... SUCCESS [  2.449 s]
[INFO] Cucumber-JVM: Android .............................. SUCCESS [ 22.400 s]
[INFO] Cucumber-JVM: Java8 ................................ FAILURE [  6.531 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by brasmusson** [comment]
> all tests seemed to pass except the final re. Java8

@jkleiser It looks like you are using v1.2.4 and have run into #912. It has been fixed in the latest v1.2.5-SNAPSHOT (from yesterday).

**Comment by jkleiser** [comment]
After a `git pull` the `mvn test` at the top level now passes all tests, incl. Java8. However, down at the examples/java-webbit-websockets-selenium I still get `Could not initialize class cucumber.examples.java.websockets.SharedDriver` after some 54 seconds.
